//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Tratamientos = new HashSet<Tratamientos>();
        }
    
        public int CitaID { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<int> MascotaID { get; set; }
        public Nullable<int> VeterinarioID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
    }
}
