//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Tratamientos = new HashSet<Tratamientos>();
        }
    
        public int CitaID { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<int> MascotaID { get; set; }
        public Nullable<int> VeterinarioID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Pets Pets { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
    }
}
