//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Tratamientos = new HashSet<Tratamiento>();
        }
    
        public int CitaID { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<int> MascotaID { get; set; }
        public Nullable<int> VeterinarioID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Veterinario Veterinario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamiento> Tratamientos { get; set; }
    }
}
