//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitaTratamiento
    {
        public int CitaID { get; set; }
        public int TratamientoID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Tratamiento Tratamiento { get; set; }
    }
}
