//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int HistorialID { get; set; }
        public Nullable<int> MascotaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<int> VeterinarioID { get; set; }
    
        public virtual Pets Pets { get; set; }
        public virtual Veterinarios Veterinarios { get; set; }
    }
}
