//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int HistorialID { get; set; }
        public Nullable<int> MascotaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<int> VeterinarioID { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Veterinario Veterinario { get; set; }
    }
}
