//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioID { get; set; }
        public string Identificacion { get; set; }
        public string Contrasenna { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdPerfil { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
