//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetLover.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veterinarios()
        {
            this.Citas = new HashSet<Citas>();
            this.HistorialMedico = new HashSet<HistorialMedico>();
        }
    
        public int VeterinarioID { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string Contrasenna { get; set; }
        public string Telefono { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string Especialidad { get; set; }
        public System.DateTime FechaContradado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialMedico> HistorialMedico { get; set; }
    }
}
